"""Eval-protocol pilots: does the paper's own `\\boxed{ANSWER}` instruction
(`re_polar/mcts/rewards.py:PAPER_INSTRUCTION`) -- suspected root cause of a real
~55% prompt-template-echo rate found in the RESCUE error analysis (see
`build_error_analysis_from_textlog.py`/`tag_with_llm.py`) -- matter, and does
an alternative do better? Several protocols, growing over the course of the
investigation:

  --protocol drllm
    DR.LLM's exact protocol (chat-wrapped -- the only mode for an instruct
    model, see `re_polar.mcts.rewards.drllm_chat_prompt`'s docstring),
    max_new_tokens=15 (DR.LLM's own data-generation default for DART-Math),
    graded with their actual import `mathruler.grader`. On Qwen3-8B this
    protocol collapses (very low accuracy, the large majority of generations
    never produce a `\\boxed{}` at all within the 15-token budget); on
    Qwen2.5-7B-Instruct (one of the models DR.LLM's own paper validated this
    on, via --model-id) it reaches much higher accuracy with ~100% boxed
    generations -- confirming it's a Qwen3-specific mismatch (narrates
    reasoning despite an explicit "no explanation" instruction), not the
    protocol being tight everywhere.

  --protocol minerva_math
    lm-evaluation-harness's minerva_math task (what most published
    MATH-benchmark papers cite numbers from) -- 4-shot raw completion with
    real worked examples (`re_polar.mcts.rewards.minerva_math_prompt`, never a
    placeholder), stop generation at "Problem:", max_new_tokens=256 (their
    HFLM default). Graded with OUR OWN `EvaluatorMath`, not their
    exact_match/math_verify metric -- prompt+budget are the faithful part,
    not a full metric reproduction like --protocol drllm is.

  --protocol paper_fewshot / --protocol drllm_fewshot
    An ablation, not a reproduction of anything external: does SHOWING
    solved examples fix format compliance on its own, independent of
    minerva_math's ~256-token CoT cost? Same 4 real MATH problems as
    minerva_math's fewshot set, but with ONLY the terse `\\boxed{X}` answer,
    no reasoning -- isolates "fewshot presence" from "CoT-vs-terse", stays at
    our own 50-token MCTS budget instead of minerva's 256. Each variant
    repeats that prompt's OWN existing per-question structure (paper's
    Problem-Start/End/Answer, or DR.LLM's Question/instruction) with a real
    worked answer, rather than inventing a new format. See
    `re_polar.mcts.rewards.paper_fewshot_prompt` / `drllm_fewshot_prompt`.

  --protocol drllm_raw / drllm_chat_prefill / drllm_chat_strict /
  drllm_chat_qwen_deadcode / paper_minimal_fewshot /
  drllm_chat_minimal_fewshot / drllm_chat_minimal_fewshot_prefill
    Follow-on variants isolating individual candidate fixes at DR.LLM's real
    15-token budget, zero-shot (no fewshot): a response-prefill trick
    (`\\boxed{` injected before generation), a one-demonstration minimal
    fewshot (a single trivial "What is 1+1? -> \\boxed{2}" turn, not 4 real
    MATH problems, to isolate near-zero-cost format nudging), and combining
    both winners together. `paper_default` and `paper_minimal_fewshot` are
    the two rows this repo's echo-sweep paper table (`tab:echo-sweep`,
    generated by `generate_echo_sweep_latex_table.py`) is actually built
    from, alongside 4 `drllm*` rows for cross-comparison; the earlier
    protocols above (`drllm`, `minerva_math`, `paper_fewshot`,
    `drllm_fewshot`) were exploratory precursors, kept here since they're
    real runnable protocols, not currently part of the paper table itself.

IDENTITY-path generation only -- no program/rescue comparison, investigates
the BASE PROMPT itself, independent of MCTS.

Data: DART-Math (`re_polar/datasets/dart_math.py`'s `dart_math_v2`-schema
`diff{N}/{split}.json` files, 500/level per split, has query_id).

    python -m analysis.error_analysis.prompt_variant_pilot --protocol drllm \\
        --n-per-difficulty 40 --output drllm_qwen3_8b.jsonl
    python -m analysis.error_analysis.prompt_variant_pilot --protocol drllm \\
        --model-id Qwen/Qwen2.5-7B-Instruct \\
        --n-per-difficulty 40 --output drllm_qwen25_7b.jsonl
    python -m analysis.error_analysis.prompt_variant_pilot --protocol minerva_math \\
        --n-per-difficulty 40 --output minerva_math_qwen3_8b.jsonl
    python -m analysis.error_analysis.prompt_variant_pilot --protocol paper_default \\
        --model qwen3_8b --dataset-dir dart_math_v2 \\
        --splits train val test --full --batch-size 16 \\
        --output full10k_paper_default_qwen3_8b.jsonl

Top-level classify_formatting/select_samples/mathruler_grade/truncate_at_stop
are stdlib-only (mathruler imported lazily) so they're unit-testable without
torch.
"""
import argparse
import json
import random
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, List, Optional

# `python -m analysis.error_analysis.prompt_variant_pilot` does not add
# this file's own directory to sys.path (unlike running it as a plain
# script), so the plain `from analysis_utils import ...` below needs it
# added explicitly -- same fix as tag_with_llm.py in this directory.
import sys
_THIS_DIR = str(Path(__file__).resolve().parent)
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)
from analysis_utils import has_unfilled_boxed_placeholder


@dataclass
class Protocol:
    prompt_style: str   # key into re_polar.mcts.rewards.PROMPT_STYLES
    max_new_tokens: int
    grader: str          # "ours" | "mathruler"
    stop: Optional[str]  # truncate generated text at first occurrence, if set
    truncate_after_boxed: bool = False  # also apply truncate_after_first_boxed (see
                                         # its docstring) -- separator-agnostic
                                         # complement to `stop`, for prompts whose
                                         # real answer is always the first (only)
                                         # thing that should be graded
    prefill: Optional[str] = None       # text injected into the PROMPT (e.g. a
                                         # response-prefill trick) that generate_all's
                                         # tokenizer.batch_decode of just the new
                                         # tokens won't include -- prepended back onto
                                         # each generation before grading/classifying,
                                         # so e.g. a prefilled "\boxed{" + generated
                                         # "42}" is correctly seen as "\boxed{42}"


PROTOCOLS = {
    "drllm": Protocol("drllm_chat", max_new_tokens=15, grader="mathruler", stop=None),
    "minerva_math": Protocol("minerva_math", max_new_tokens=256, grader="ours", stop="Problem:"),
    # stop="\n\n": both fewshot prompts join blocks with a blank line (see
    # paper_fewshot_prompt/drllm_fewshot_prompt) -- MUST truncate there, not at a
    # marker further into the block (e.g. "### Problem Start"/"Question:"), because
    # a hallucinated continuation that gets cut off mid-instruction (common at only
    # 50 tokens) would otherwise leave a second, unfilled \boxed{...} in the text
    # that extract_boxed's last-match behavior then grabs INSTEAD of the real
    # answer -- caught via a local smoke test (a genuinely correct \boxed{2008}
    # answer graded wrong because of exactly this). truncate_after_boxed
    # additionally handles hallucinations with NO blank-line separator at all (e.g.
    # Qwen2.5-7B-Instruct: "\boxed{(6,1)} Solve the following math problem...",
    # caught on the first full-scale run, 3-11/200 samples across all four fewshot
    # runs -- see truncate_after_first_boxed's docstring).
    "paper_fewshot": Protocol("paper_fewshot", max_new_tokens=50, grader="ours", stop="\n\n",
                               truncate_after_boxed=True),
    "drllm_fewshot": Protocol("drllm_fewshot", max_new_tokens=50, grader="ours", stop="\n\n",
                               truncate_after_boxed=True),
    # These four isolate one candidate explanation each for why DR.LLM's chat-wrapped
    # protocol collapses on Qwen3-8B but works on Qwen2.5-7B-Instruct, all still at
    # DR.LLM's real 15-token DART budget, zero-shot, no fewshot. mathruler grading
    # kept for direct comparability against the "drllm" faithful row they're all
    # trying to beat.
    "drllm_raw": Protocol("drllm_raw", max_new_tokens=15, grader="mathruler", stop=None,
                           truncate_after_boxed=True),  # raw has no chat turn boundary to
                                                         # stop hallucination -- same class
                                                         # of risk as the fewshot prompts
    "drllm_chat_prefill": Protocol("drllm_chat_prefill", max_new_tokens=15, grader="mathruler",
                                    stop=None, prefill="\\boxed{"),
    "drllm_chat_strict": Protocol("drllm_chat_strict", max_new_tokens=15, grader="mathruler",
                                   stop=None),
    "drllm_chat_qwen_deadcode": Protocol("drllm_chat_qwen_deadcode", max_new_tokens=15,
                                          grader="mathruler", stop=None),
    # ONE trivial demo (What is 1+1? -> \boxed{2}), not 4 real MATH problems --
    # near-zero token cost if it works, the cheapest possible thing to actually
    # adopt. mathruler grading (DR.LLM wording) / ours (paper wording) to match
    # each one's own comparison anchor.
    "paper_minimal_fewshot": Protocol("paper_minimal_fewshot", max_new_tokens=50, grader="ours",
                                       stop="\n\n", truncate_after_boxed=True),
    "drllm_chat_minimal_fewshot": Protocol("drllm_chat_minimal_fewshot", max_new_tokens=15,
                                            grader="mathruler", stop=None),
    # Combine BOTH winners -- prefill on top of the minimal-fewshot prompt. Only the
    # REAL question's answer is prefilled (the demo turn already has its own
    # complete answer baked in as real chat history).
    "drllm_chat_minimal_fewshot_prefill": Protocol(
        "drllm_chat_minimal_fewshot_prefill", max_new_tokens=15, grader="mathruler",
        stop=None, prefill="\\boxed{"),
    # Our own CURRENT PRODUCTION prompt (PAPER_INSTRUCTION, \boxed{ANSWER}, raw, 50
    # tok) -- every other row here needs this as the actual reference point.
    "paper_default": Protocol("raw", max_new_tokens=50,  # PAPER_MAX_NEW_TOKENS in rewards.py;
                               grader="ours", stop=None),  # hardcoded here, not imported, to
                                                            # keep heavy imports inside main()
}


def select_samples(rows: List[dict], n: int, rng: random.Random) -> List[dict]:
    """Round-robins across `source` (math/gsm8k) for balance, same policy as
    select_and_generate.py's _round_robin_by_source but against dart_math_v2's flat
    record schema (source is top-level, not nested under sample_info)."""
    by_source: Dict[str, List[dict]] = defaultdict(list)
    for s in rows:
        by_source[s.get("source", "unknown")].append(s)
    for v in by_source.values():
        rng.shuffle(v)
    sources = list(by_source)
    selected: List[dict] = []
    i = 0
    while len(selected) < n and any(by_source.values()):
        src = sources[i % len(sources)]
        if by_source[src]:
            selected.append(by_source[src].pop())
        i += 1
    return selected


def truncate_at_stop(text: str, stop: Optional[str]) -> str:
    """`generate_all` (select_and_generate.py) has no stop-string support -- greedy
    generation runs the full max_new_tokens regardless, so a few-shot prompt's
    completion can bleed into a hallucinated NEXT question. This mirrors what
    lm-eval-harness's `until` stopping achieves for grading purposes: only the text
    before the first occurrence of `stop` is the model's actual answer."""
    if not stop:
        return text
    return text.split(stop, 1)[0]


def truncate_after_first_boxed(text: str) -> str:
    """Cut `text` right after the FIRST complete `\\boxed{...}` span closes (brace-
    depth matching, same approach as re_polar/vendor/dart_math/eval.py's extract_boxed).
    A stricter, separator-agnostic complement to truncate_at_stop: caught on the
    fewshot ablation runs -- `stop="\\n\\n"` missed cases where a model (esp.
    Qwen2.5-7B-Instruct) hallucinated a next question WITHOUT a blank-line separator
    (e.g. "\\boxed{(6,1)} Solve the following math problem..."), leaving a second
    unfilled \\boxed{ANSWER} that extract_boxed's last-match behavior then grabbed
    instead of the real, correct, already-generated answer -- affected 3-11/200
    samples across all four fewshot runs (`generated_text.count("oxed{") > 1`).
    For our terse-fewshot prompts the real answer is always the FIRST and ONLY thing
    that should be graded -- nothing after it was ever wanted. No-op if `text` has
    zero or exactly one boxed span (nothing to disambiguate; also avoids needlessly
    stripping legitimate trailing punctuation like a closing "." in the common case)."""
    if text.count("oxed{") < 2:
        return text
    prefix, rest = text.split("oxed{", 1)
    depth = 1
    i = 0
    for i, c in enumerate(rest):
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                break
    return prefix + "oxed{" + rest[:i + 1]


def classify_formatting(extract_boxed_fn: Callable[[str], Optional[str]], text: str) -> dict:
    has_boxed = "oxed{" in text
    boxed_content = (extract_boxed_fn(text) or "").strip() if has_boxed else ""
    return {
        "has_boxed": has_boxed,
        "boxed_content": boxed_content,
        "boxed_empty": has_boxed and boxed_content == "",
        "is_placeholder_echo": has_unfilled_boxed_placeholder(text),
    }


def mathruler_grade(gt: str, text: str) -> bool:
    """DR.LLM's exact grading call: extract the boxed span, grade with
    mathruler's symbolic checker. Wrapped in try/except -- mathruler is
    sympy-based like our own vendored grader, which has a documented
    pathological-input blow-up risk (re_polar/mcts/rewards.py's GRADE_TIMEOUT_S
    docstring); DR.LLM's own code has no such guard, but a bare try/except
    costs nothing."""
    from mathruler.grader import extract_boxed_content, grade_answer
    try:
        pred = extract_boxed_content(text.strip())
        return bool(pred) and bool(grade_answer(pred, gt))
    except Exception:
        return False


def grade_all_pooled(refs: List[str], texts: List[str], workers: int = 4) -> List[bool]:
    """Grade the whole "ours"-protocol batch through re_polar.core.grader's memory-capped
    subprocess pool -- the same primitives GenerationReward._grade_batch
    (re_polar/mcts/rewards.py) already uses for MCTS reward grading -- instead of calling
    the grader directly in this process.

    Why this matters at full-corpus scale: EvaluatorMath.extract_ans's
    strict_extract behavior (deliberately NOT patched, to preserve
    reproduction fidelity with PoLar's own identically-behaved grader) means
    even a boxed generation can fall through to a "last number in the whole
    response" speculative extraction; occasionally that speculated "number"
    is a giant expression whose sympy comparison tries to allocate tens of
    GB (see re_polar/core/grader.py's own docstring). Calling the grader in-process
    has no guard against that. Every grade here instead runs in its own
    worker with an 8GB RLIMIT_AS cap and a 5s timeout (GRADE_MEM_BYTES/
    GRADE_TIMEOUT_S, re_polar/mcts/rewards.py) -- a pathological answer is
    contained to one worker (recycled per GRADE_MAX_TASKS) and scored 0,
    exactly like MCTS's own reward path already handles it, instead of
    taking the whole job down."""
    import multiprocessing as mp
    from pebble import ProcessPool
    from re_polar.core.grader import _grade_worker, _grade_worker_init
    from re_polar.mcts.rewards import GRADE_MAX_TASKS, GRADE_MEM_BYTES, GRADE_TIMEOUT_S

    n = len(refs)
    results: List[Optional[bool]] = [None] * n
    remaining = list(range(n))
    pool = None
    n_done = 0
    for attempt in range(2):  # persistent pool, then at most one rebuild on a break
        if not remaining:
            break
        if pool is not None:
            try:
                pool.stop()
            except Exception:
                pass
        pool = ProcessPool(max_workers=workers, max_tasks=GRADE_MAX_TASKS,
                            context=mp.get_context("spawn"),
                            initializer=_grade_worker_init, initargs=(GRADE_MEM_BYTES,))
        futures: Dict[int, object] = {}
        try:
            for i in remaining:
                futures[i] = pool.schedule(_grade_worker, args=(refs[i], texts[i]),
                                            timeout=GRADE_TIMEOUT_S)
        except Exception:
            pass  # pool broke mid-schedule -> unscheduled indices stay in `remaining`
        still: List[int] = []
        for i in remaining:
            fut = futures.get(i)
            if fut is None:
                still.append(i)
                continue
            try:
                results[i] = bool(fut.result())
            except Exception as e:
                pool_broke = ("Broken" in type(e).__name__) or isinstance(e, OSError)
                if pool_broke and attempt == 0:
                    still.append(i)  # collateral of a pool break -> retry once, don't mislabel
                else:
                    results[i] = False  # contained timeout/expiry, or final -> genuine 0
            n_done += 1
            if n_done % 500 == 0 or n_done == n:
                print(f"  graded {n_done}/{n}", flush=True)
        remaining = still
    for i in remaining:  # defensive: unresolved even after the rebuild -> 0
        results[i] = False
    if pool is not None:
        pool.stop()
    return results


def main(argv=None):
    # heavy imports INSIDE main() (mirrors select_and_generate.py)
    from re_polar.models import MODEL_REGISTRY
    from re_polar.core.layer_engine import LayerEngine
    from re_polar.mcts.rewards import PROMPT_STYLES
    from re_polar.vendor.dart_math.eval import extract_boxed

    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from select_and_generate import generate_all  # noqa: E402

    p = argparse.ArgumentParser()
    p.add_argument("--protocol", required=True, choices=list(PROTOCOLS))
    p.add_argument("--dataset-dir", default="dart_math_v2")
    p.add_argument("--difficulty", type=int, action="append", default=None,
                   help="1-5 (repeatable); default 1-5")
    p.add_argument("--n-per-difficulty", type=int, default=40)
    p.add_argument("--splits", nargs="+", default=["test"], choices=["train", "val", "test"],
                   help="which dart_math_v2 splits to pull from per difficulty; default "
                        "test only (500/difficulty, matches every pilot run so far)")
    p.add_argument("--full", action="store_true",
                   help="use ALL samples per difficulty across --splits, ignoring "
                        "--n-per-difficulty entirely (e.g. --splits train val test --full "
                        "= the complete 10,000 on disk -- train(1250)+val(250)+test(500) "
                        "per difficulty x 5; NOT the full ~14,941-query pre-binning pool, "
                        "which was never materialized on disk -- the paper's echo-sweep "
                        "table only ever needed the released 10,000)")
    p.add_argument("--model", default="qwen3_8b",
                   help="MODEL_REGISTRY key; ignored if --model-id is given")
    p.add_argument("--model-id", default=None,
                   help="raw HF model id, bypasses MODEL_REGISTRY (e.g. for a model "
                        "outside this repo's registry, such as Qwen2.5-7B-Instruct "
                        "cross-checks against the DR.LLM protocol)")
    p.add_argument("--trust-remote-code", action="store_true", default=None,
                   help="only used with --model-id; default True")
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--grade-workers", type=int, default=4,
                   help="pool size for grade_all_pooled (grader='ours' protocols only; "
                        "'mathruler' protocols grade in-process, see mathruler_grade's "
                        "docstring). Matches GenerationReward's memory-capped subprocess "
                        "pattern (re_polar/mcts/rewards.py).")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--output", required=True)
    args = p.parse_args(argv)

    protocol = PROTOCOLS[args.protocol]
    difficulties = args.difficulty or [1, 2, 3, 4, 5]
    rng = random.Random(args.seed)

    selected: List[dict] = []
    for d in difficulties:
        rows: List[dict] = []
        for split in args.splits:
            path = Path(args.dataset_dir) / f"diff{d}" / f"{split}.json"
            rows.extend(json.loads(path.read_text()))
        if args.full:
            selected.extend(rows)
        else:
            selected.extend(select_samples(rows, args.n_per_difficulty, rng))
    print(f"Selected {len(selected)} samples across difficulties {difficulties} "
          f"({args.n_per_difficulty}/difficulty)", flush=True)
    if not selected:
        raise SystemExit("No samples selected -- nothing to do.")

    if args.model_id:
        model_id = args.model_id
        trust_remote_code = True if args.trust_remote_code is None else args.trust_remote_code
    else:
        if args.model not in MODEL_REGISTRY:
            raise SystemExit(f"Unknown model {args.model!r}; known: {sorted(MODEL_REGISTRY)}")
        cfg = MODEL_REGISTRY[args.model]
        model_id = cfg["model_id"]
        trust_remote_code = cfg.get("trust_remote_code", True)
    print(f"=== protocol={args.protocol!r} model_id={model_id!r} "
          f"prompt={protocol.prompt_style} max_new_tokens={protocol.max_new_tokens} "
          f"grader={protocol.grader} stop={protocol.stop!r} ===", flush=True)

    engine = LayerEngine(model_id, trust_remote_code=trust_remote_code)
    tokenizer = engine.tokenizer
    if tokenizer.padding_side != "left":
        tokenizer.padding_side = "left"
    identity_path = list(range(engine.num_layers))

    questions = [s["question"] for s in selected]
    gts = [s["gt_ans"] for s in selected]

    raw_texts = generate_all(engine, tokenizer, engine.device, PROMPT_STYLES[protocol.prompt_style],
                              identity_path, questions, protocol.max_new_tokens, args.batch_size,
                              label=args.protocol)
    if protocol.prefill:
        raw_texts = [protocol.prefill + t for t in raw_texts]
    texts = [truncate_at_stop(t, protocol.stop) for t in raw_texts]
    if protocol.truncate_after_boxed:
        texts = [truncate_after_first_boxed(t) for t in texts]

    if protocol.grader == "mathruler":
        from mathruler.grader import extract_boxed_content as extract_fn
        print(f"Grading {len(texts)} samples (mathruler, in-process)...", flush=True)
        corrects = [mathruler_grade(gt, text) for gt, text in zip(gts, texts)]
    else:
        extract_fn = extract_boxed
        print(f"Grading {len(texts)} samples (pooled, {args.grade_workers} "
              f"memory-capped workers)...", flush=True)
        corrects = grade_all_pooled(gts, texts, workers=args.grade_workers)
    print(f"Grading done: {sum(corrects)}/{len(corrects)} correct.", flush=True)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    n_correct = n_has_boxed = n_boxed_empty = n_placeholder_echo = 0
    with open(out_path, "w") as f:
        for s, gt, text, correct in zip(selected, gts, texts, corrects):
            fmt = classify_formatting(extract_fn, text)
            rec = {
                "protocol": args.protocol,
                "model_id": model_id,
                "query_id": s["query_id"],
                "difficulty": s["difficulty"],
                "source": s.get("source"),
                "question": s["question"],
                "gt_ans": gt,
                "generated_text": text,
                "correct": correct,
                **fmt,
            }
            f.write(json.dumps(rec) + "\n")
            n_correct += int(correct)
            n_has_boxed += int(fmt["has_boxed"])
            n_boxed_empty += int(fmt["boxed_empty"])
            n_placeholder_echo += int(fmt["is_placeholder_echo"])

    n = len(selected)
    print(f"Wrote {n} records -> {out_path}", flush=True)
    print(f"\n=== Summary (protocol={args.protocol}, model={model_id}, "
          f"identity-path generation) ===", flush=True)
    print(f"n={n}  accuracy={n_correct / n:.1%}  has_boxed={n_has_boxed / n:.1%}  "
          f"boxed_empty={n_boxed_empty / n:.1%}  placeholder_echo={n_placeholder_echo / n:.1%}",
          flush=True)


if __name__ == "__main__":
    main()
